### PR TITLE
Implementing strong n4 itk biasfield correction

### PR DESCRIPTION
**Pull request by sl609**

### CODE REVIEW

**Comment by drewclements** [comment]
@sl609 This branch runs fine, but I did notice on all of my test subject reports that vent defects are much higher than reports generated by the main branch. There are also substantial discrepancies between this and the main branch for Mem:Gas & RBC:Gas ratios. Attached are the reports as an example of how this new branch is visually missing parts of the mask & how it compares to main branch.

[009-020_report_test_main.pdf](https://github.com/user-attachments/files/16640212/009-020_report_test_main.pdf)
[009-020_report_test.pdf](https://github.com/user-attachments/files/16640213/009-020_report_test.pdf)

**Comment by sl609** [comment]
The code should not effect the Mem and RBC which is something I originally thought especially when you look at the commits. (Only change ventilation distribution and bias field).

I am not saying Drew is wrong in fact he is correct and Good catch on this.
The reason the mem and rbc output are different is probably because we use the mask_vent which is derived from gas image as the following.

    def gas_binning(self):
        """Bin gas images to colormap bins."""
        self.image_gas_binned = binning.linear_bin(
            image=img_utils.normalize(self.image_gas_cor, self.mask),
            mask=self.mask,
            thresholds=self.config.reference_data.threshold_vent,
        )
        self.mask_vent = np.logical_and(self.image_gas_binned > 1, self.mask)
        
      We can see that the mask_vent is depended on image_gas_binned which is again derived image_gas_cor from Strong Biasfield correction.

**Comment by sl609** [comment]
This is not bugged but I think we need to discuss about how we should deal with this? like changing mask_vent to just mask?

**Comment by sl609** [comment]
I am going to add David on this for discussion

**Comment by drewclements** [comment]
To add more context, my previous comment was tested with manual masks. Attached are runs with CNN mask, but it doesn't change any behavior from what I described (however, the font changes when running current branch with CNN but that is probably irrelevant)
[009-020_report_test_CNN.pdf](https://github.com/user-attachments/files/16640586/009-020_report_test_CNN.pdf)
[009-020_report_test_main_CNN.pdf](https://github.com/user-attachments/files/16640587/009-020_report_test_main_CNN.pdf)

**Comment by sl609** [comment]
Drew confirmed that the mask_vent is the issue. The point of discussion now is whether and how to change it

**Comment by davidmummy** [comment]
@sl609 I'm not quite following this. 

In the original example provided by @drewclements , he used the same manual mask and got very different vent defect maps, which went from 7% on the main branch to 28% on the test branch. 

This will of course affect the mem_mean and rbc_mean, because the regions of ventilation defect are excluded from those calculations. 

This subject does not appear to have a coil placement problem, and the "new" defects are mostly in the base of the lung. I think the question is whether this behavior is correct or not, with the "strong" N4ITK. I would have expected that this subject wouldn't have changed much, given the vent images.  

@drewclements did I get that right?

**Comment by sl609** [comment]
I think the Strong Biasfield works as expected as you can see from the shift to the right (and higher mean) in ventilation histogram. The high ventilation is due to the change in using the new healthy reference. The old reference (Ziyi) is more forgiven which explain why we change to back to that version

**Comment by bdriehuys** [comment]
Its worth looking at the grey-scale image a little more carefully here. I do agree that this is one case where the old pipeline and the old reference distribution do a generally better job than the new. I suspect a big part of this case is that it was an incomplete or imperfect inhalation as evidenced by the super bright trachea. I suspect part of this could be our top percentile rescaling as much as it is the new bias field correction and reference. I think fundamentally, we just need to look at a lot more cases to see if this is a major outlier or if this is a trend. 
Vent Montage

**Comment by davidmummy** [comment]
Completely agree on making sure this isn't just an outlier. I don't think the trachea is included in the rescaling in either case, however, since as far as I know that is only done within the mask? I suppose "hot bronchi" that make their way into the mask could still be throwing things off, though.

**Pull request merged**
