### PR TITLE
Iowa complex conjugate

### PR DESCRIPTION
**Pull request by sl609**

### CODE REVIEW

**Comment by sl609** [comment]
[Cinci_Iowa_mrddata.zip](https://github.com/user-attachments/files/16618458/Cinci_Iowa_mrddata.zip)
Cinci and Iowa testing data

**Comment by davidmummy** [comment]
I am testing this on MRDs I have created from Duke subject 007-031. I get this error when I try to run the modified pipeline: 

AttributeError: type object 'IOFields' has no attribute 'SYSTEM_VENDOR'

It does not appear that SYSTEM_VENDOR was declared in class IOFields in io_utils.py. 

Can you confirm & if true, fix this? 

(These same MRDs work just fine using the production pipeline).

**Comment by davidmummy** [comment]
I've confirmed this works on Duke, Cincy, and Iowa MRDs. Excellent!

However, when I go back to try to run a regular twix file (regression testing), I get this error: 

raceback (most recent call last):
  File "main.py", line 116, in <module>
    app.run(main)
  File "/Users/mummy/opt/anaconda3/envs/XeGas/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/mummy/opt/anaconda3/envs/XeGas/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "main.py", line 107, in main
    gx_mapping_reconstruction(config)
  File "main.py", line 38, in gx_mapping_reconstruction
    subject.reconstruction_gas()
  File "/Users/mummy/code_consortium/xenon-gas-exchange-consortium/subject_classmap.py", line 339, in reconstruction_gas
    system_vendor = self.dict_dis[constants.IOFields.SYSTEM_VENDOR]
KeyError: 'system_vendor'

@sl609 can you confirm whether you also get this error when processing a Duke Twix subject on this branch?

**Comment by sl609** [comment]
Good Catch David!!! Yep we totally forgot about Twix file. I fix that now (2 commits). Hopefully it is done for good !!

**Comment by sl609** [comment]
> Good Catch David!!! Yep we totally forgot about Twix file. I fix that now (2 commits). Hopefully it is done for good !!

@davidmummy

**Comment by davidmummy** [comment]
Completed testing on MRDs from all three platforms. Orientation correct in all cases! Fix for twix file has solved the issue. Merging and closing. Many thanks to @sl609 and @fuyaoli-lisa for all your work on this.

**Pull request merged**
